# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('civilite', models.CharField(choices=[('Monsieur', 'M.'), ('Madame', 'Mme'), ('Mademoiselle', 'Mlle')], max_length=4)),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
                ('prenom', models.CharField(blank=True, max_length=120, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('regime', models.CharField(blank=True, max_length=40, null=True)),
                ('situation_familliale', models.CharField(blank=True, max_length=40, null=True)),
                ('adresse1', models.CharField(blank=True, max_length=120, null=True)),
                ('adresse2', models.CharField(blank=True, max_length=120, null=True)),
                ('code_postal', models.IntegerField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=120, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('numero_securite_sociale', models.IntegerField(blank=True, null=True)),
                ('date_effet', models.DateField(default=datetime.date(2018, 5, 6))),
            ],
        ),
    ]
