# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarification', '0002_auto_20180506_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_effet',
            field=models.DateField(default=datetime.datetime(2018, 5, 6, 21, 29, 30, 789052, tzinfo=utc)),
        ),
    ]
