# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tarification', '0003_auto_20180506_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_effet',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
