# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('civilite', models.CharField(choices=[('MR', 'M.'), ('MME', 'Mme'), ('MLLE', 'Mlle')], max_length=4)),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
                ('prenom', models.CharField(blank=True, max_length=120, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('regime', models.CharField(blank=True, max_length=40, null=True)),
                ('situation_familliale', models.CharField(blank=True, max_length=40, null=True)),
                ('adresse1', models.CharField(blank=True, max_length=120, null=True)),
                ('adresse2', models.CharField(blank=True, max_length=120, null=True)),
                ('code_postal', models.PositiveIntegerField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=120, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15, null=True)),
                ('date_effet', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.CharField(blank=True, max_length=120, null=True)),
                ('options', models.CharField(blank=True, max_length=120, null=True)),
                ('date_de_paiement', models.PositiveIntegerField(blank=True, null=True)),
                ('mode_de_paiement', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='type_date_de_paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='type_mode_de_paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, max_length=240)),
            ],
        ),
    ]
