# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-21 19:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('civilite', models.CharField(choices=[('MR', 'M.'), ('MME', 'Mme'), ('MLLE', 'Mlle')], max_length=4, null=True)),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
                ('prenom', models.CharField(blank=True, max_length=120, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('regime', models.CharField(blank=True, max_length=40, null=True)),
                ('situation_familliale', models.CharField(blank=True, max_length=40, null=True)),
                ('adresse1', models.CharField(blank=True, max_length=120, null=True)),
                ('adresse2', models.CharField(blank=True, max_length=120, null=True)),
                ('code_postal', models.PositiveIntegerField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=120, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^0[0-9]{9}$', 'Le num\xe9ro doit \xeatre du type 0123456789')])),
                ('email', models.EmailField(max_length=254)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^0[0-9]{9}$', 'Le num\xe9ro doit \xeatre du type 0123456789')])),
                ('date_effet', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.CharField(blank=True, max_length=120, null=True)),
                ('options', models.CharField(blank=True, max_length=120, null=True)),
                ('date_de_paiement', models.PositiveIntegerField(blank=True, null=True)),
                ('mode_de_paiement', models.CharField(blank=True, max_length=120, null=True)),
                ('categorie_produit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contrat.CategorieProduit')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
                ('nom_commercial', models.CharField(blank=True, max_length=120, null=True)),
                ('identifiant', models.CharField(blank=True, max_length=6, null=True)),
                ('compagnie_assurance', models.CharField(blank=True, max_length=120, null=True)),
                ('email_compagnie_assurance', models.EmailField(max_length=254)),
                ('branche', models.CharField(blank=True, max_length=120, null=True)),
                ('encaissement', models.CharField(blank=True, max_length=120, null=True)),
                ('profession', jsonfield.fields.JSONField(blank=True, default='', null=True)),
                ('regime', jsonfield.fields.JSONField(blank=True, default='', null=True)),
                ('condition_age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_age_min_conj', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_age_max_conj', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_age_min_enfant', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_age_max_enfant', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_regime', models.CharField(blank=True, max_length=400, null=True)),
                ('condition_code_postal', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDateDePaiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TypeModeDePaiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_zone', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
                ('liste_code_postal', models.CharField(blank=True, max_length=400, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('dictionnaire_prix', jsonfield.fields.JSONField(blank=True, default='', null=True)),
                ('id_produit', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contrat.CategorieProduit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='type_contrat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contrat.TypeContrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='produit',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contrat.Produit'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_contrat',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contrat.TypeContrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='zone_produit',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='contrat.ZoneProduit'),
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='id_produit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contrat.Produit'),
        ),
    ]
