# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-21 19:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='code_postal',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^0[0-9]{9}$', 'Le num\xe9ro doit \xeatre du type 0123456789')]),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='zone_produit',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='contrat.ZoneProduit'),
        ),
    ]
