# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 22:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^0[0-9]{9}$', 'Le num\xe9ro doit \xeatre du type 0123456789')], verbose_name='Num\xe9ro de t\xe9l\xe9phone'),
        ),
    ]
