# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-21 20:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0004_auto_20180721_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='code_postal',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('[0-9]{5}$', 'Le num\xe9ro doit \xeatre du type 01234')]),
        ),
    ]
