# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0005_auto_20180721_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='profession',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='regime',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
