# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0006_auto_20180722_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorieproduit',
            old_name='id_produit',
            new_name='produit',
        ),
    ]
