# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0007_auto_20180725_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='categorie_produit',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='produit',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='zone_produit',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
